### ISSUE TITLE
incorrect privacy api 

### ISSUE THREAD

**Issue by danmarsden** [appalachianstate/moodle-local_ganalytics#1]
This plugin passes user data to an external service (Roles etc.) - so it should really be implementing the add_external_location_link functions as specified here:
https://docs.moodle.org/dev/Privacy_API

One example of a plugin that does this is here:
https://github.com/catalyst/moodle-tool_coursebank/blob/master/classes/privacy/provider.php

**Comment by woolardfa** [comment]
Thanks @danmarsden for the input. I can see how this may apply, but let me ask, shouldn't the distinction between personally identifying information and run-of-the-mill user data (e.g. role) be made? Maybe my error is looking at this more through the lens of (US) FERPA, rather than GDPR, which I have not read. I will be happy to implement the suggested provider if you think GDPR was meant to cover application defined user characteristics with no personally identifying information. I certainly don't want to represent that this tool can provide a way to export or erase any of it, true?

Another consideration... the MoodleDoc you referenced mentions that configurable items do not necessarily need to be described using the privacy API; all of the data items exported by this plugin are configurable via custom coding?

**Comment by danmarsden** [comment]
I may have incorrectly assumed it wasn't just "Role" that was being passed to Google - although I do think that the role has the potential for identifying a user, especially when certain roles are only assigned to a small subset of users in a course (eg teacher/tutor/etc) - but I'm far from being an expert on this either.

The main point of the external_location_link api is for the report shown to the Moodle privacy officer to cover all information about users that is shared with external systems.

If you think it's not needed - feel free to close as won't fix.

**Comment by woolardfa** [comment]
@danmarsden let's say I buy in to the notion of role being personally identifiable, then I have to say the course name is likewise (only one student enrolled), and course size (only one course with one student, all the rest have 15 or more), and course category (just because)... in for a penny, in for a pound... i'll identify all four sample dimension items as user data sent to an external service. Like you said, the main point is to let the privacy offer know what is shared and leave the determination to that person. Thanks for all the feedback.

**Comment by woolardfa** [comment]
Corrected. Thanks for the suggestion.
